### ISSUE TITLE
Centos problem

### ISSUE THREAD

**Issue by forkgood** [victor-oliveira1/zippyshare_downloader#1]
I try to download some file at centos,But there seems to be a mistake. Does CentOS need to add "--show-progress" after WGet?

[root@localhost ~]# ./zippyshare_downloader.sh 'http://www85.zippyshare.com/v/1j3tVis4/file.html'
./zippyshare_downloader.sh: line 13: **: syntax error: operand expected (error token is "**")
Baixando: TBO &amp; Vega ft. Alex - Lambada (Ibiza Mix) - [www.nowosci-mp3.eu].mp3     Tamanho: 9.73 MB
**wget: unrecognized option '--show-progress'**
Usage: wget [OPTION]... [URL]...

Try ‘wget --help’ for more options.

**Comment by victor-oliveira1** [comment]
Hello!

The problem is:
Zippyshare changes its download form every day or week.
The code i've made have worked on the past month, but now it's broken.
I will update today.

Thanks for contacting.


Em 16-05-2017 11:28, forkgood escreveu:

**Comment by victor-oliveira1** [comment]
Hello again!
Script updated, problem solved.

**Comment by victor-oliveira1** [comment]
Hello!
I'm reviving this issue to say a word:
I've rewritten from scratch in Python3!
And we don't have more problems about the website changing how auth number is calculated
